---
date-modified: last-modified
---

# Anastesiformer

## Intravenös anestesi

### TCI --- Target Controlled Infusion

Förstahandsval vid intravenös anestesi.

Önskad målkoncentration av läkemedel ställs in efter ålder och kroppsvikt för
propofol samt ålder, kroppsvikt, längd och kön för remifentanilinfusion.

**Normal arbetsgång vid TCI:**

1. Antikolinergika ges, preoxygenering startas.
2. Propofolinfusionen startas.
3. När propofolets Ce nått 0,2--0,4µg/ml startas remifentanilinfusionen
    - Om alfentanil används ges istället bolusdos varpå infusion startar.
4. Vid Tubintubation ges muskelrelaxantia då patienten inte reagerar vid
   beröring eller på kornealstimulering.
5. Intubera efter muskelrelaxantia fått effekt.

### TIVA --- Total IntraVenous Anaesthesia

### RSI --- Rapid Sequence Induction

Utförs då man bedömer att risk för aspiration föreligger.

- Svåra refluxbesvär
- Icke-fastande patient
- Gravid
- Ileus
- Appendicit



## Gasanestesi

<!--
Detta är em kommentar

-->

## Malign hypertermi

Ärftlig sjukdom som ger extrem kalciumfrisättning vid tillförsel av vissa anestesiläkemedel.

**Orsakas** av sevoflourin och celukorin.

###### Symtom

- Påtaglig stelhet i käkleder
- Muskelstelhet i hela kroppen
- Tecken till sönderfall av muskelvävnad
- Ökad kaliumhalt i blodet
- Snabbt stigande utandad CO~2~
- Snabbt ökande O~2~-behov
- Hög puls, svettning
- **Snabb** feber, upp till 1 grad/minut.

##### Behandling

- Avbryt införsel av narkoslm
- Ge motmedel --- Dantrolen^[Ryanodinreceptor]
- Sätt in IVA-åtgärder efter symtom.
