# Chock

|**Chocktyp**|**Mekanismer**|
|:---|:---|
|**Hypovolem**|Blödning<br>Dehydrering|
|**Obstruktiv**|Massiv lungemboli<br>Övertryckspneumotorax<br>Tamponad|
|**Kardiogen**|Arytmi<br>Nedsatt myokardfunktion<br>Strukturella problem|
|**Distributiv**|Sepsis^[Har en mer komplex bild då man kan få blödning, hjärtpåverkan, mikroembolisering och vasodilatation samtidigt.]<br>Anafylaktisk<br>Neurogen chock<br>Akut binjurebarkssvikt|

Chock uppträder då syretillförseln till organ ej uppnår deras behov.
Definitionsmässigt ska *symtom* från minst 2 organsystem föreligga.

|**Mekanism**|**Effekt**|
|:---|:---|
|**Positiv ino-/krontotropi**|Takykardi
|**Konstriktion av resistens- och kapacitanskärl**|Diastolisk tryckstegring|
|**Retention av natrium och vatten**||
|**Perifer insulinresistens och glukoneogenes**|Ökad extracellulär glukoskoncentration.<br>Drar vätska till extracellulärrummet via osmos.

- **Generella chocksymtom**
    - Blekhet
    - Kallsvettig
    - Takypné
    - Takykardi
    - Kalla extremiteter
    - Marmorerad hudkostym
    - Hypotoni
    - Medvetandepåverkan
    - Avsaknad av puls vid lågt systoliskt tryck
        - Radialis --- ~90
        - Femoralis --- ~70
        - Carotis --- ~60

### Initialt omhändertagande

- **ABCDE**
- **Anamnes**
- **Blodprov**
- **EKG**
- **Bedside-ULJ**

Ordinera syrgas, adekvat vätska och tidiga läkemedel (t.ex adrenalin vid tecken
på anafylaktisk chock) *samtidigt* som ovanstående utförs!

### Generell behandling

- **Inotropa läkemedel**
    - Dobutamin
    - Adrenalin
- **Vätska**
    - Kristalloid
    - Kolloid
    - Blod
- **Perifer vasokonstriktion**
    - Noradrenalin

## Hypovolem chock

|**Blodförlust**|**Effekter**|
|:---|:---|
|**10--15%**|Inga|
|**15--30%**|Oro/Ångest<br>Takypné<br>Takykardi<br>Blekhet<br>Fördröjd kapillär återfyllnad|
|**30--40%**|Konfusion<br>Ökad takypné<br>Blekhet<br>Kyla|
|**>40%**|Ofta medvetslöshet|

##### Kliniska drag/Diagnos

- **Tecken/symtom**
    - *Tidiga:*
        - Andningskorrelerad variation i blodtryckskurvan --- Kan ses redan när
        andra symtom saknas.
        - Minskad pulsamplitud pga ökat diastoliskt tryck och bibehållet
        systoliskt. Perifera pulsationer blir alltså svagare innan systoliskt
        blodtryck börjar falla.
        - Takykardi --- HF > Systoliskt blodtryck = allvarligt, ofta efter
        1,5--2 liters blödning.
        - **Äldre** sjunker ofta i systoliskt tryck med mindre/utan ovanstående
          varningstecken.
- **Undersökningar**
    - *ULJ:*
        - *V. cava inferior* < 2cm eller kollapsgrad > 50%^[Kan även tala för
        distributiv chock. Motsatsen talar för kardiogen eller obstruktiv chock.]

##### Behandling

* **Volymersättning**
    - *1 liter blodförlust kan ersättas med:*
        - 2 SAGMAN + 0,5L kolloid
        - 1L Kolloid
        - 4L Kristalloid
        - 2L Kristalloid + 0,5L kolloid

