# Prostata

## Benign prostatahyperplasi

I stort sett alla män får förr eller senare någon grad av BPH. Tillväxten av
prostata sker genom hyperplasi. Denna sker ffa i *transitionszonen*. Korrelation
mellan storlek, obstruktion och symtom är svag.

Det finns ingen konsensus om exakt vad BPH är (förutom den histopatologiska
diagnosen), hur man får det och varför symtom
uppträder.


##### Kliniska drag/Diagnos

- **Symtom**
  - LUTS, ffa lagringssymtom
  - Hematuri --- Kan förekomma men ska föranleda *samma utredning som vid
  hematuri utan BPH*
  - Skelettsmärta vid metastaserande sjkd.
- **Status**
  - Förstorad prostata vid pr
- IPSS-score, dryckes-/miktionslista
- Flödesmätning
- Urodynamisk utredning vid misstanke om andra orsaker till symtom^[Parkinson,
rest efter stroke, MS m.fl]
- **Bilddiagnostik**
  - Cystoskopi *vid atypiska symtom*
  - Resurinkontroll
  - TRUL *vid cancermisstanke*
- **Labb**
  - PSA
  - Krea

::: {.callout-tip}

## Diffdiagnoser

- Prostatit
- Blåshalsskleros
- Uretrastriktur
- Prostatacancer
- Blåssten

:::

##### Behandling

Kirurgi, medicinsk alternativt kronisk kateter/RIK.

**IPSS** kan guida:             
Under 8p -> exspektans           
8--18p -> Medicinsk Behandling         
Över 18p -> Kirurgisk behandling

- **Medicinsk behandling**
  - *Finasterid* --- 5-alfa-reduktashämmare som minskar konvertering av
  teestosteron till DHT. Kan krympa prostata med 30% över 3--6 månader.
  Rekommenderas till körtlar >40g. PSA ska reduceras med 50% efter 6 månaders
  behandling.
  - *Alfuzosin* --- Alfa-receptorblockerare som relaxerar glatt muskulatur i
  blåshals och prostatisk uretra. Ger effekt inom 14 dagar. Mer
  biverkningar^[Yrsel, huvudvärk m.fl]. Försiktighet till äldre, kärlsjuka och
  de med falltendens!
  - *Tolterodin* --- Antikolinergika som minskar blåskontraktilitet och lindrar
    lagringssymtom. CAVE gällande urinretention.
  - *Mirabegron* --- Betareceptorblockerare med samma verkningsmekanism som
  Tolterodin.
- **Kirurgisk behandling**
  - *TURP* --- TransUretral Resektion av Prostata
  - *Transvesikal adenomenukleation* --- Öppen operation vid storlek >100g.
  - *TUMT* --- TransUretral MikrovågsTerapi, skonsam behandling med nästan samma
    effekt som TURP.


::: {.callout-tip}

## När ska PSA ordineras?

- Palpatorisk misstanke om prostatacancer
- Ökande skelettsmärta hos män > 40
- Allmänna cancersymtom
- Hereditär risk
  - 2 eller fler i familjen m. PrCa
  - Män med känd BRCA2-mut
  - Män med mutation i G84E i HOXB13
- Män som efter adekvat information önskar testas
  - [Adekvat information](https://cancercentrum.se/globalassets/cancerdiagnoser/prostatacancer/om-psa-prov-for-att-upptacka-prostatacancer-i-ett-tidigt-skede-tryckfardig.pdf)
- Behandlingskrävande LUTS hos män med > 10 års förväntad överlevnad. Alternativt då symtom ökat påtagligt under senaste året.

:::

## Prostatacancer

Vanligaste cancerformen bland män.          

Drygt 50% av 50~60 åringar har prostatacancer i obduktionsstudier. De allra
flesta kommer inte dö/få symtom av det.

::: {.callout-tip}

## PSA

**Normalvärden:**

- **<70:** <3 mikrogram/L
- **70-80:** <5 mikrogram/L
- **>80:** <7 mikrogram/L

Män med högre PSA än ovanstående bör remitteras till urolog. Malgnitetssuspekt
palpationsfynd bör föranleda misstanke oavsett PSA-värde.           
Män >50 med PSA 2,0--2,9 bör följas upp med PSA vartannat år.

**Felkällor:**

- Urinstämma --- Ger omedelbar höjning, ofta dubblering. Dock sällan >20µg/L.
- UVI --- Kan ge kraftigt förhöjda värden.
- 5-alfareduktashämmare --- Sänker PSA vid BPH. 

$PSAdensitet = \frac{PSAvärde}{körtelvolym}$ 

PSA-densitet > 0.15 stärker malignitetsmisstanke.

:::

##### Kliniska drag/Diagnos

Var frikostig med misstanke hos äldre män vid skelettsmärta och symtom från
området kring prostatan (t.ex LUTS, obehag i perineum m.m).

###### Undersökningar

- **Biopsi:**
  - Kan guidas med MR. Annars sticks på 12 ställen enligt schema. Gör ont och
    är jobbigt för patienten.
- **MR**
  - Röntgenläkare sätter PI-RADS 1-5, ju högre desto högre misstanke om kliniskt relevant cancer.
- **PSMA-PET-CT**
  - Utförs ffa på höggradiga tumörer (cT3^[**c**T3 = klinisk bedömning, **p**T3 = patologens bedömning] alt. Gleason > 4+3 = 7 i mer än 50%
  av *systematiska* biopsier *eller* i riktade biopsier vid PI-RADS 5 alt. PSA > 20).

## Blåscancer

**Alla** > 50 med makrohematuri ska utredas för blåscancer! Även många <50 ska
utredas.            
Vid plötsliga UVI-symtom utan påvisbar infektion bör man tänka lite på cancer.

##### Kliniska drag/Diagnos

###### Misstanke



##### Behandling

- **TUR-B** --- Trans Uretral Resektion av Blåsa aka hyvling.
- **BCG** --- Sprutas in i blåsan mha tappningskateter. Ger ibland
blås-tuberkulos och ofta UVI-/Cystitsymtom.
Var frikostig med misstanke hos äldre män vid skelettsmärta och symtom från området kring prostatan (t.ex LUTS, obehag i perineum m.m).
- **FDG-PET-CT**

###### Rekonstruktion

- **Bricker**
- **Lundiana**
