project:
  type: book
  output-dir: docs
language: customlang.yml
book:
  title: "KM3"
  date: "2023-09-07"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Ortopedi"
      chapters:
        - allmänfraktur.qmd
        - övreextr.qmd
  search:
    location: sidebar
    type: textbox

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    number-depth: 3
    comments:
      hypothesis: true
  pdf:
    documentclass: scrreprt



