project:
  type: book
  output-dir: docs
language: customlang.yml
book:
  title: "KM3"
  date: "2023-09-07"
  cover-image: cover.jpg
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Ortopedi"
      chapters:
        - allmänfraktur.qmd
        - övreextr.qmd
        - nedreextr.qmd
  appendices:
    - ordlista.qmd
  search:
    location: sidebar
    type: textbox


format:
  html:
    theme:
      light: [flatly, boktheme.scss]
      dark: [darkly, boktheme.scss]
    number-depth: 3
    comments:
      hypothesis: true
  pdf:
    documentclass: scrreport
    number-depth: 3



