project:
  type: book
  output-dir: docs
language: customlang.yml
book:
  title: "KM3"
  date: "2023-09-07"
  cover-image: cover.jpg
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - part: "Ortopedi"
      chapters:
        - ortopedi/ortostatus.qmd
        - ortopedi/allmänfraktur.qmd
        - ortopedi/övreextr.qmd
        - ortopedi/nedreextr.qmd
        - ortopedi/rygg.qmd
    - part: ortopedi/barnortopedi.qmd
      chapters: 
        - ortopedi/barnnedreextr.qmd
    - part: "Urologi"
      chapters:
        - urologi/urostatus.qmd
        - urologi/akutskrotum.qmd
        - urologi/hematuri.qmd
        - urologi/stensjukdom.qmd
        - urologi/uvi.qmd
        - urologi/penis.qmd
        - urologi/njurexpans.qmd
        - urologi/prostata.qmd
        - urologi/tumörer.qmd
    - part: "Anastesi"
      chapters:
        - anestesi/anestesiformer.qmd
        - anestesi/vätskebalans.qmd
        - anestesi/läkemedel.qmd
        - anestesi/preopbedömning.qmd
        - anestesi/luftväg.qmd
        - anestesi/chock.qmd
        - anestesi/dödförklaring.qmd
  appendices:
    - ordlista.qmd
  search:
    location: sidebar
    type: textbox


format:
  html:
    mainfont: Liberation Serif
    theme:
      light: [flatly, boktheme.scss]
      dark: [darkly, boktheme.scss]
    number-depth: 3
  pdf:
    documentclass: scrreprt
    mainfont: Liberation Serif
    sansfont: Liberation Serif
    number-depth: 3
  epub:
    toc: true
    creator: "Elias Sjölin"
    number-depth: 3
    css: boktheme.scss
