# Nedre extremiteten

## Bäcken

### Bäckenfraktur

Sker i princip antingen vid osteoporostillstånd+lågenergivåld eller hos unga
efter högenergivåld. Efter lågenergivåld är de nästan alltid stabila och läker
komplikationsfritt. Efter högenergivåld är de nästan alltid
instabila/dislocerade.

##### Kliniska drag/Diagnos

**Stabil bäckenfraktur:** Kan likna odislocerad höfrfraktur vilket måste
uteslutas.         

**Instabil bäckenfraktur:** Pat är ofta svårt smärtpåverkad. Ofta kombinerad med
inre kärlskador samt skador på bukorgan. Pat kan ej stödja på benen. Livshotande.

Förutsatt att patienten är stabil ställs diagnos via rtg/trauma-DT beroende på
omständigheter.

##### Behandling

**Stabil fraktur** kräver endast symtomatisk behandling. Belastning går bra så fort
smärtan tillåter.           

**Instabil fraktur** behandlas nästan alltid med öppen reposition och fixation. I
väntan på dessa bör ett instabilt/dislocerat bäcken komprimeras med gördel för
att hindra blödning.
Instabil fraktur utan felställning kan *ibland* behandlas med avlastning i 12v.                 

##### Prognos

Äldre patienter har liknande risk som vid höftfraktur. Även de med stabila
frakturer uppnår tidigare funktionsnivå i bara ca 50% av fall.              
Engagerar frakturen acetabulum finns stor risk för artrosutveckling.

Vid instabil fraktur avgör associerade skador ofta prognosen. En stor andel av
dessa patienter blir inte återställda.

#### Ramusfraktur

##### Behandling

Konservativ om ramus ej är helt av. Op med stabilisering om instabil.

## Höft

### Höftfraktur

En av de vanligaste och allvarligaste fragilitetsfrakturerna. 1-årsmortaliteten
är **25%**.

::: {.callout-tip}

## Klassifikation

Delas ffa in efter lokalisation.

- **Cervikal**
  - Delas vidare in enl Garden I-IV. I praktiken gäller odislocerad(I-II) eller
    dislocerad(III-IV). Vid dislocerad cervikal fraktur är risken för
  cirkulatorisk påverkan hög.
  - Valgus impact --- Kompression med valgusfelställning. Kärlmässigt okej.
- **Trokantär/Pertrokantär**
- **Subtrokantär**

:::

##### Kliniska drag/Diagnos

- Förkortat, utåtroterat ben
- Smärta

::: {.callout-warning}

## Missas ibland

Inkilade frakturer och stressfrakturer behöver inte vara felställda och
patienten kan ofta belasta dem! Smärta kan ha funnits en längre tid. Särskilt
vid stressfrakturer.         
Smärtan kan ibland också upplevas endast i knät.^[Pat. med knäsmärta utan fynd
-> Undersök höft!]

:::

Verifieras i första hand med röntgen. Vid stark klinisk misstanke och negativ
röntgen bör MR utföras.

##### Behandling

Kirurgisk behandling, helst inom 24h.^[Pga lägre mortalitet ju lägre väntetid.] Mobilisering snabbast möjligt i nästan
alla fall.          
Rehab i ett antal månader.

- **Cervikal** --- **Alla** nya frakturer ska opereras. Vid äldre odislocerad
fraktur kan icke-kirurgisk behandling övervägas.
  - **Odislocerad**
    - Lätt valgusfelställning kan fixeras direkt. Andra reponeras. Fixering sker
      med skruvar eller pinnar från lateralsidan **inom 12h**.
  - **Dislocerad**
    - Hög risk för skador på kärl längs *collum femoris* med störd läkning som
    följd. **Äldre**(>65) behandlas därför alltid med protes. Unga behandlas i
    allmänhet med LIH.
  - **Basocervikal**
    - Samma som pertrokantära.
- **Pertrokantär** --- 2-fragmentfraktur läker ofta lätt. >2 fragment ökar instabilitet och risk för felställning.
  - Oftast glidskruv/twinhook+platta. Märgspik+collumskruv ger mer komplikationer.
  - Fraktur som endast ses på MR kan ofta behandlas icke-kirurgiskt.
  - **Isolerad trokantär fraktur** --- Endast avlösning av *trokanter major*
    - Smärtlindring+mobilisering
- **Subtrokantär**
  - Lång märgspik med glidskruv och biaxial glidning. Risk för blodförlust!

##### Prognos

Läker på ca 3-4mån i normalfallet. Full återhämtning tar betydligt längre tid.

::: {.callout-warning}

## Komplikationer

- **Redislokation**
- **Utskärning/Cut-out** --- Skruv "skär" ut ur caput pga hög belastning.
- **Lateral glidning** --- För hög kompression av frakturen efter osteosyntes.
Kan ge ljumsk/glutealsmärta och likna kaputnekros och pseduartros!
- **Kaputnekros** --- Vanligast efter cervikal fraktur. Kan uppstå åratal efter
  originalskadan. Ger sig till känna med vil-/belastningssmärta (oftast) efter
en tids symtomfrihet. Röntgenfynd kommer sent i förloppet. MR visar tidigare.
Kan finnas som rtg-bild utan symtom. Symtomgivande kaputnekros behandlas med
höftprotes.
- **Pseudartros** --- Misstänks vid fortsatt svår smärta och försämrat röngtenläge 3-4mån
  efter fraktur. Behandlas med höftprotes.
- **Implantatnära fraktur** --- Risk vid märgspik och höftprotes. Om protesen
inte är lös kan den sitta kvar.

:::

### Luxation/Instabilitet


## Lår

### Diafysär femurfraktur

::: {.callout-tip}

## Klassifikation

Enl AO/OTA:

**A:** Enkel fraktur        
**B:** Fraktur med böjkil           
**C:** Kommplex fraktur


[A-B kan vidare delas in i 1-3.](https://www.orthobullets.com/trauma/1040/femoral-shaft-fractures)

Uppdelning efter energimängd vid trauma finns även.

:::

Utgör ca 5% av alla femurfrakturer. Vanligaste patienten är en osteoporosdam som
fallit i samma plan. Även yngre kan drabbas efter högenergivåld.            
Skadan kan ge livshotande blödning.

Kompartmentsyndrom är ovanligt. Muskelnekroser kan dock ge *crush syndrome* med
elektrolytrubbningar och njursvikt som följd.

##### Kliniska drag/Diagnos

- trauma
- Oförmåga att belasta
- Smärta som ökar i rörelse
- Konsistensökning av låret (pga blödning - upp till 1,5L)

::: {.callout-note}

## Fynd

- frakturkrepetationer
- Instabilitet
- Felställning
- Förkortning
- **Gör distalstatus**

:::

::: {.callout-important}

## OBS

**Uteslut andra skador!** --- t.ex knä, höft, kotpelare, thorax.

:::

**Diagnos** bekräftas med röntgen av **hela femur inkl. höft och knä** (alt.
trauma-DT).

##### Behandling

Enl. ATLS vid högenergiskada.

Öppna frakturer bör tvättas och stabiliseras operativt snarast.
Antibiotikaprofylax är viktigt.
**Stabilisering** --- Bästa smärtlindringen. Hindrar blödning -> mindre
inflammation.       
Jämfört andra skador vid högenergivåld har frakturen låg prio förutom när det
gäller att hindra blodförlust.          

Icke kirurgisk behandling är i princip aldrig rekommenderad.            
Vid implantat i femur sedan tidigare måste implantaten överlappa för att undvika
ytterligare fraktur i benet mellan dem.

Vid lågenergitraum används ofta antegrad(satt från trochanter) märgspik.

Vid högenergitrauma används *Early Total Care* med märgspik om patienten tål det. Annars görs minsta möjliga åtgärd i akutskedet.

##### Prognos

Ju mer splittrad/instabil desto sämre prognos. Vid multitrauma är prognosen
beroende av övriga skador.

Läkningstid är 4-5mån.

Benlängdsförkortning, rotationsfelställning, *delayed union* och *non
union*/pseudartros är möjliga komplikationer.             
Vid *non-union*/pseudartros friseras frakturytorna och fixering sker med grövre
märgspik.               
Om märgspikar ger smärta kan de plockas ut.

### Stressfraktur

Förekommer i bäcken, lårbenshals, femurdiafys.          
Specialvariant återfinns i **atypisk subtrokantär femurfraktur** som ses vid
långvarig bisfosfonatbehandling (och eventuellt andra osteoporosbehandlingar).

##### Kliniska drag/Diagnos

Förloppet börjar med ospecifik smärta vid belastning. Denna uppstår med fortsatt
belastning även i vila. I normalfallet ses ej svullnad.

::: {.callout-note}

## Fynd

- Smärta vid provokation av påverkad skelettdel
- Smärta vid hopp på ett ben
- Normal rtg tidigt

:::

Då rtg är normal i tidigt skede bör ny utföras efter 2-4v. MR eller scint kan
visa förändringar direkt.

##### Behandling

- Minska aktivitet
  - Lättare träning okej så länge den ej ger smärta
- Vid utebliven smärtfrihet gäller total vila i 4-6v.
- **Vid stressfraktur i lårbenshalsen:**
  - Akut op. med skruvfixation pga hög risk för dislokation och
  läkningsstörning.

##### Prognos

Läker oftast väl utan resttillstånd (undantaget i lårbenshals!). Fysisk
aktivitet bör undvikas tills man är helt smärtfri.

## Knä

### Distal femurfraktur

Utgör ca 5% av alla femurfrakturer. Orsakas av sidovinkling, rotation och
axiellt våld i kombination. Ofta efter fall på flekterat knä. Incidenstoppar är
unga män efter högenergivåld och äldre kvinnor efter fall i samma plan.

::: {.callout-note}

## Klassifikation

- **A** Extraartikulär fraktur med intakt knäled.
- **B** Delvis intraartikulär.
- **C** Splittrad fraktur med ledengagemant

:::

##### Kliniska drag/Diagnos

::: {.callout-tip}

## Fynd

- Synlig felställning
- Palpömhet och smärta vid rotationprovokation
- Kraftig svullnad av lån/knä
- **Distalstatus**

:::

Rtg bekräftar diagnos. Ofta sätts dorsal gipsskena innan rtg.

##### Behandling

I allmänhet kirurgisk. Vid minimal felställning alternativt gravt sjuk pat med
osteoporotiskt skellett kan sträckbehandling/helbensgips övervägas. Mobilisering
beroende på skada, fixationstyp och belastning. Äldre mobiliseras om möjligt
direkt efter op. Osteoprosrelaterade frakturer hos äldre bör handläggas lika
skyndsamt som en höftfraktur.

* **A**: Retrograd märgspik alternativt skruvfixation med platta.
* **B:** Skruvfixation + eventuellt platta.
* **C:** Glidskruv + platta, distal femurplatta alternativt kombo med skruv och
  märgspik. C3 är svårbehandlade och har dålig prognos även med behandling.

**Följs upp** med rtg var 6-8:e vecka tills full läkning.

##### Prognos

Läker på ca 3-5 månader.

### Patellafraktur

Förekommer i alla åldersgrupper.

Patella omges lateralt/medialt av quadricepssenans
förlängning/extensorretinaklen. Det betyder att även vid tvärgående fraktur kan
extensionsförmåga finnas kvar.

Uppkommer i princip på 3 sätt:

1. Plötslig flektion av knät ger reflexiv quadricepskontraktion som leder till
   fraktur.
2. Direkt våld mot ett böjt knä.
3. Medial avulsionsfraktur kan ske hos unga vid patellaluxation.

##### Kliniska drag/Diagnos

Smärta framtill i knät som ökar i rörelse efter ovanstående trauma bör inge misstanke.

::: {.callout-note}

## Fynd

- Palpömhet, ibland med kontinuitetsavbrott
- frakturkrepetationer
- Smärta medialt/lateralt tyder på skada mot extensorretinaklet
- Oförmåga/förmåga att sträcka i knäleden?

:::

Diagnos fås genom rtg.          
En hel patella som ligger kranialt/kaudalt kan tyda på ruptur av
patellar-/quadricepssenan.          
Ett normalfynd är *patella bipartia* där det finns en liten "extrapatella" vid
patellas överkant. Frakturer har skarpa kanter till skillnad från *patella
bipartia*.

##### Behandling

- Punktion för evakuering av hematom.
- **Bevarad sträckfunktion** --- Rtg-kontroll efter 3-6 veckort vid
icke-kirurgisk behandling.
  - Längsgående: Reducerad aktivitet i 3-6 veckor. Fullt rörelseomfång tillåts.
  - Tvärgående/splittrade: Låst ortos i 3-6 veckor. Belastning axialt och
  quadricepsträning är ok.
- **EJ bevarad sträckfunktion** --- Behandlas kirurgiskt.
  - Tvärfraktur och komminut fraktur med dislokation >3-4mm och/eller hak i
  ledytan >2-3mm opereras m. cerklage och pinnar. Vid stabil fixation tillåts
  viss belastning och träning omedelbart efter operation. Vid tveksam stabilitet
  används låst ortos i 3-6 veckor.
  - Vid tvärfraktur vid patellans övre pol tas det övre fragmentet bort och
  senan fixeras vid den kvarvarande patellan följt av temporärt cerklage.

##### Prognos

De flesta återfår full funktion och läker på 8 veckor. Viss risk finns för att
osteosyntesmaterial släpper. Komplikationer är ovanliga. Ytligt
osteosyntesmaterial ger dock ofta retning och tas då bort.

### Proximal tibiafraktur

::: {.callout-tip}

## Klassifikation

- **A** --- Utan ledengagemang
- **B** --- Med ledengagemang
- **C** --- Ledengagerande fraktur som avlöser båda kondylerna/splitterfraktur
med ledengagemang.

:::


##### Kliniska drag/Diagnos

- Patienten stödjer inte på det skadade benet.
- Palpation ger smärta och frakturoljud om splittrad fraktur.
- Ibland kraftig svullnad av knä och underben.
- Vid stabilitetstest i vissa fall uppenbar instabilitet i varus/valgus.
- Eventuellt öppen skada med genomstickssår eller utstickande benändar.
- Nerv- och kärlskador förekommer med påverkat distalstatus.

Slätröntgen bekräftar diagnos. Ofta DT inför operation.

##### Behandling

- **Öppen fraktur, Kompartmentsyndrom, Kärlskada** är absoluta indikationer för
  operation.
- **A** --- Operation eller gips
- **B** --- Ofta operation. Steg i ledyta >10mm hos äldre/5mm hos yngre är stark
  indikation.
- **C** --- I princip alltid operation.

Vid gips/ortosbehandling utförs rtg-kontroll efter 1-2v. Avgipsning efter ca 6
veckor.

Efter behandling bör belastning undvikas då risk för dislokation är stor vid
axiell belastning.

##### Prognos

Generellt sett god även vid allvarligare frakturer. Ca 75% uppnår gott resultat. Rehabtid dock upp till 1 år.

Komplikationer inkluderar kärl-/nervskador, kompartmentsyndrom, instabilitet,
tidig artros och postoperativ infektion.

### Broskskada

Kan vara ytlig eller djup (=går ned till skelettet). Uppkommer ofta i
kombination med andra knäskador. Återfinns i 85-90% av fall på den mediala
konylen. Oftast hos barn.

##### Kliniska drag/Diagnos

Symtomen är ofta lindriga till att börja med och påminner om meniskskada och går
ofta kliniskt ej att skilja från sådan.

- Smärta vid belastning
- Upphakningar
- Krepetationer
- Svullnad

Diagnos bekräftas med **MR**.

##### Behandling

Behandling bestäms utifrån skadans omfattning samt relevans för symtom. Viktigt
att skilja från begynnande artros.

- **Ytliga skador/Skador < 2cm^2^** --- Debridering och abrasion -> (ofta)
mikrofrakturering.
- **Djupa/stora skador** --- Ett antal [behandlingar](https://www.internetmedicin.se/behandlingsoversikter/ortopedi/broskskador/) är möjliga. Efter dessa
undviks belastning i 4-8v varefter denna successivt ökar under upp till 6
månader.

##### Prognos

Ofta gott korttidsresultat. På lång sikt varierar det beroende på behandling.

### Luxation

#### Knäledsluxation

Sällsynt men allvarligt. Ofta tillsammans med skada på ett kollateralligament
och båda korsbanden.

##### Kliniska drag/Diagnos

::: {.callout-note}

## Fynd

- Svullnad (m. dominans lateralt/medialt)
- Uttalad instabilitet
- Oförmåga att stödja på benet
- **Distalstatus**
    
:::

Vid misstänkt kärlskada utreds detta akut med doppler/angiografi. Efter att
kärl-/nervskada uteslutits bekräftas diagnos med Rtg(utesluter fraktur), MR
(värdera ligamentskada) samt DT vid avulsionsfraktur eller [eminentiafraktur](https://orto.nu/injury.php?id=knee_eminence).

##### Behandling

- **Kärlskada** --- Ofta akut kärlkirurgi
- **Ligamentskada** --- Rekonstrueras tillsammans med ev. meniskskada/korsbandsskada semiakut.

##### Prognos

Ofta >1 års rehab. Ofta uppnås ett stabilt knä med nedsatt rörlighet/funktion.
Artrosrisk är stor. Nervskada är ofta bestående och kan ge t.ex droppfot.

#### Patellaluxation

Förekommer ffa efter slag mot mediala delen av knäskålen kombinerat med
utåtrotation av tibia samt lårbensmuskelaktivering^[t.ex vid tackling i
idrottssammanhang.].

Går alltid ur led åt lateralsidan. Drar även sönder ledkapseln och ledband på
insidan av leden.

##### Kliniska drag/Diagnos

**Akut** luxation ger kraftig smärta i knäleden. Vid undersökning kan patella
ligga kvar eller ha spontanreponerats.

::: {.callout-note}

## Fynd

- Hemartros
- Ev. luxerad patella
- Uttalad ömhet över patellas mediala kan

:::

Rtg visar ibland små benbitar som avlösts från patella/femur.           
CT/MR kan visa övriga mjukdelsskador och eventuella broskskador hos barn som
växer.

##### Behandling

**Reponering** sker ofta spontant. Annar utförs den genom att trycka på
patella samtidigt som knät sträcks.

- **Förstagångsluxation utan lösa fragment** --- Kortvarig immobilisering (t.ex
ortos).
- **Med lösa fragment** --- Ofta akut operation.

Muskelstärkande träning är alltid rekommenderad.

##### Recidiverande patellaluxation

Drabbar främst kvinnor. Är i allmänhet minimalt smärtsamt. Rtg/MR görs ej
rutinmässigt, dock inför ställningstagande till operation.

###### Behandling

I första hand träning. Eventuellt stabiliserande operation.

###### Prognos

Om besvärsfrihet ej uppnås med träning ger operation i allmänhet stabilitet med
full funktion. Dock finns ökad risk för artrosutveckling.

### Sidoledbandsruptur

Uppkommer i ofta efter vridvåld i idrottssammanhang, ibland efter att man landar
med benet vikt på foten som vrider sig. Även snedtramp kan orsaka skadan.

::: {.callout-tip}

## Klassifikation

- **Grad I** --- <5mm skillnad i sidovackling jmf friskt ben.
- **Grad II** --- 5-10mm skillnad.
- **Grad III** --- >10mm skillnad. Här finns ofta även andra skador
(meniskskada, främre korsband).

:::

##### Kliniska drag/Diagnos

Pat kommer ofta med gångsvårigheter och ett knä som känns ostabilt och viker sig.

::: {.callout-note}

## Fynd

- Svullnad --- Sällan vid grad I, hemartros tyder på samtidig ACL-skada.
- Palpationsömhet över sidoledband --- Ofta så pass uttalad att ordentlig
undersökning ej låter sig göras i akutskedet.
    - Ofta över fästet på femur.
- Skillnad vid vacklingsprov --- Jämför alltid med frisk sida!

:::

Rtg utesluter fraktur. Vid misstanke om tibiakondylfraktur kan DT utföras. **MR
vid misstanke om skada på fler strukturer**.

##### Behandling

- **Isolerad grad I-II** --- Ortos med full rörelse/belastning/träning i 1-6
veckor. Undvik NSAID.
- **Grad III** --- Ofta kirurgisk behandling beroende på skadans karaktär.
Ibland finns ruptur av senfästen kring knät. Detta är en indikation för akut
kirurgi om funktionell stabilitet ska bevaras.
- **Äldre/låga funktionskrav** --- Ortos i 6-8v -> träning.

##### Prognos

Oftast bra funktion efter 6-12v. Upp till 1 år innan full funktion återfås.

### Främre korsbandsskada

Inträffar vanligtvis vid vridskador under idrott. Vanligast hos unga kvinnor.           
Ca 20-50ggr vanligare än bakre korsbandsskada.

::: {.callout-tip}

## Klassifikation

- **Grad I-III** beroende på grad av sagitell rörelse mellan *tibia* och *femur*

:::

##### Kliniska drag/Diagnos

Pat kommer med tilltagande smärta, svullnad, instabilitet och rörelseinskränkning. Ofta
beskriver pat att något "hände" i knät vid skadetillfället. 

::: {.callout-note}

## Fynd

- Positivt främre draglådetest samt Lachmans test.
- Positivt *pivot-test* --- Patognomt för ACL-skada.
- Fynd som tyder på menisk, sidoledbandsskada m.fl
  - Över 50% av ACL-skador är kombinerade med andra skador.
- Svullnad
  - Hemartros är ACL-skada tills motsatsen bevisats!

:::

Rtg bör utföras för att utesluta fraktur. Vid klinisk misstanke om ACL-skada
utför MR.

##### Behandling

Beror på ålder, aktivitetsnivå och skadeläge.

- **icke-kirurgisk** --- 3-6mån rehab samt aktivitetsanpassning-
  - Vid *give-way* episoder och nedsatt funktionsförmåga trots rehab kan nytt
  ställningstagande till op tas.
- **Primär stabiliserande op** --- Barn, unga fysiskt aktiva, de med tyngre
jobb.
  - Barn m. *eminentiafraktur*^[[Se -@sec-eminentia]] bör opereras inom 1 vecka. Hos övriga är optimal
    tid då knät svullnat av och rörelseförmåga återfåtts.^[Tidigare finns ökad
  risk för ärrbildning i knät(artrofibros).]

##### Prognos

Det finns ökad risk för artros oavsett behandling. Upprepade
subluxationer/*give-way*-episoder ökar risk än mer varför dessa bör opereras.

**Graftruptur** sker hos 3% av all och *20%* av unga kvinnor.

## Underben

### Diafysär tibiafraktur

Finnes ofta tillsammans med fibulafraktur. I "*underbensfraktur*" ingår isolerad
tibiafraktur, kombinerad tibia/fibulafraktur men inte isolerad fibulafraktur.

::: {.callout-tip}

## Klassifikation

Klassificeras enligt A-B samt I-IIIC (Gustilo-Anderson) vid öppna frakturer.

:::

##### Kliniska drag/Diagnos

Trauma -> Smärta, oförmåga att gå/stå, nedsatt cirkulation/nervpåverkan distalt samt eventuell felställning ger misstanke.

Rtg(Frontal+sida inklusive knä och fotled) bekräftar diagnos. Vid svårighet att avgöra om frakturen engagerar led kan DT användas.

##### Behandling

**Odislocerad fraktur:**        
Helbensgips i ca 4 veckor. Rörelseträning i fot/knäled så fort som möjligt.
Alternativt operation för snabbare mobilisering.

**Dislocerad fraktur:**        
I första hand grov märgspik med låsskruvar. Plattfixation kan användas vid t.ex
komminuta frakturer men ger högre risk för utmattningsbrott av osteosyntesmaterial
och större mjukdelspåverkan.        
Öppna frakturer med liten mjukdelsskada kan ofta opereras direkt. Vid större
mjukdelsskada används ofta extern fixation medan skadan täcks av
hudlambåer/revideras.

Även lätt dislocerade frakturer löper stor risk att dislocera under läkningen!(*särskilt om fibula är helt*)          

##### Prognos

Sluten fraktur läker på ca 4 månader. Öppen fraktuer läker på ca 6-8 månader.               
Komplikationer som *delayed-/non-union* är ovanligt efter märgspikning. Smärta i
knät där man satt spiken är dock vanligt. Rotationsfelställning förekommer ffa
om tvärskruvar inte används.

### Distal tibiafraktur

::: {.callout-tip}

## Klassifikation

* **A** --- Enbart metafysärt engagemang
* **B** --- Metafysär fraktur med delvis ledengagemang
* **C** --- Metafysär fraktur med multipla ledengagemang

:::

##### Kliniska drag/diagnos

Traum som följs av smärta, oförmåga att stödja ger misstanke.

**Diagnos** ges av slätröntgen med frontal-, sido- och vridprojektioner av
fotled+underben. DT-kartläggning bör ske inför operation.

##### Behandling

**Odislocerad fraktur:**        
Underbensgips/ortos i 8-12v. Undvik belastning i minst 6 veckor.

**Dislocerad fraktur/Frakturer med ledengagemang:**         
Oftast plattfixation med mål att återskapa ledytan. Gips/ortos används i
efterloppet och belastning undviks i 8v.

##### Prognos

Associerad med hög risk för komplikationer och nedsatt funktion. Dock stor
variation beroende på skadetyp och ffa skademekanism.

### Akut kompartmentsyndrom

Ökat vävnadstryck i ett slutet rum leder till sänkt perfusion. Vid
perfusionstryck kring 30-40mmHg finns stor risk för ischemi och nekros som i sig
ökar svullnaden och späder på problemen.

Kan orsakas av gips, bandage, trauma m. blödning, svullnad m.m. Speciellt
vanligt i samband med tibiafrakturer!

##### Kliniska drag/Diagnos

* Tilltagande oproportionerlig smärta som ej svarar på smärtlindring
* Ökad svullnad och Konsistens
* Parestesier
* Palpationsömhet
* Som regel normal kärlstatus distalt

Vid misstanke med osäkerhet bör intrakompartmentell tryckmätning utföras. I
synnerhet på medvetslösa/sövda patienter!

## Fot

Vissa Weber A och B samt alla C opereras. A1 och B1 behöver aldrig opereras.

Belastning är tillåtet förutsatt att stabilitet skapats. Undantaget svåra
C-frakturer och patienter med osteoporotiskt skelett.

### Fotledsfraktur

::: {.callout-tip}

## Ottawakriterierna

100% sensitivitet, 20-50% specificitet.

US är indicerad vid:

- **Smärta runt malleolerna**...
  - ...samt palpömhet vid: Bakre randen av laterala malleolen *eller* oförmåga att belasta 4 steg.
- **Smärta i mellanfoten**...
  - ...samt palpömhet vid: Basen av metakarpalben V *eller* över båtbenet *eller* oförmåga att belasta 4 steg.

Använd **inte** på: Barn<18, vid intoxikation, Multipla smärtsamma(distraherande) skador, gravida, skallskada, neurologiska bortfall.

:::
