# Övre extremiteten

## Överarmen

### Diafysär humerusfraktur

Uppstår **oftast** till följd av direkt våld men ses även vid t.ex armbrytning och polisgrepp.      
Eventuell felställning beror på frakturens lokal. Distala och proximala frakturer ger ofta mer felställning pga muskelfästen som drar i fragment.

::: {.callout-tip}

## Klassifikation

Görs enl. AO/OTA och delas in i ABC samt grad 1-3:       
**A** --- 2-fragmentsfrakturer      
**B** --- 3-fragmentsfrakturer      
**C** --- Komminutfrakturer         

Siffra (1-3) beror på svårighetsgrad.
:::

*N. radialis*påverkan är relativt vanligt då nerven går nära diafysen. Även tryck från hematom och gips kan påverka den! De flesta radialispareser är dock övergående.

##### Kliniska drag/Diagnos

Fraktur bör misstänkas hos en patient som klagar på smärta/nedsatt rörelseförmåga i överarmen efter trauma.

Vid undersökning ses ofta direkt/indirekt smärta, felställning och frakturkrepetationer.        
**Distalstatus** ska alltid ingå i undersökningen!

Diagnosen bekräftas med röntgen av hela humerus.

##### Behandling

Som regel kan diafysära humerusfrakturer behandlas konservativt.        
Gipsskena samt ortos och slynga kombinerat med armens egen vikt kan ofta hålla den rät och hindra felställning samt förkortning.       
Efter ca 4 veckor med gips kan slutbehandling ske med ortos som omsluter humerus.

**Indikationer för kirurgi är:**

- Vinkelfelställning > 20 grader
- Förkortning > 3cm
- Öppen fraktur 
- Kärlskador
- Multipla frakturer (Där kirurgisk stabilisering underlättar mobilisering)
- Patologisk fraktur 
- *Non-union* av äldre fraktur

Operativ behandling är oftast märgspik eller plattfixation.

Vid radialispares efter sluten fraktur kan nervfunktion väntas återkomma inom 3 månader. Explorativ kirurgi utförs endast efter denna tidsgräns samt neurofysiologisk undersökning (Görs *alltid* öppen fraktur som opereras).

##### Prognos

Läker i genomsnitt på 12v.      
Långa och sneda frakturer(inkl. komminut) läker bättre än korta, tvära.         
<10% kräver kirugisk behandling. Är frakturen rörlig efter **4 månader** klassas den som *non-union*.

## Armbågen

### Olekranonfraktur {#sec-olekranonfraktur}

TODO: detta

Olekranonfrakturer ingår i proximala ulnafrakturer tillsammans med
Koronoidfraktur ([Kapitel -@sec-koronoidfraktur]) och proximal skaftfraktur.
Dessa uppkommer oftare tillsammans med andra skador jämfört med
olekranonfrakturer.

::: {.callout-tip}
## Klassifikation

- **Extraartikulära** --- ca 10%, proximal avulsionsfraktur (~avlösning av triceps)
- **Intraartikulära** --- Indelas enl. Morrey
  - Typ I --- Odislocerad
  - Typ II --- Dislocerad, stabil
  - Typ III --- Dislocerad, instabil
    - Utgör ca 15% av fall. Engagerar *proc. coronoideus* och
    kollateralligament, **mycket instabil**.

:::

##### Kliniska drag/Diagnos

Som vid andra armbågsfrakturer. Pat. saknar förmåga att extendera i
armbågsleden. Röntgen bekräftar diagnos.

##### Behandling

**Odislocerad typ I-fraktur:** Gips i 3 veckor. En dislocering på ett par mm
medför behov av operation!          
**Typ II-fraktur:** Kan behandlas konservativt hos patient med låga-måttliga
funktionskrav. (Dvs saknar behov av att aktivt extendera armbågen)          
**Typ III-fraktur:** Opereras *alltid* med reposition och fixation. Cerklage,
eller stift+cerklage och platta kan användas.

##### Prognos

Med adekvat behandling ses ofta god funktion efter läkning med viss kvarstående
rörelseinskränkning (ffa i extension).

### Koronoidfraktur {#sec-koronoidfraktur}

TODO: detta

## Underarmen

### Diafysär underarmsfraktur {#sec-diafysärunderarmsfraktur}

::: {.callout-tip}
## Klassifikation

Enligt AO/OTA:          
**A**: Enkla tvågragmentsfrakturer      
**B**: Frakturer med fjärilsformat/triangulärt intermediärfragment          
**C**: Komplexa, komminuta frakturer
:::

##### Kliniska drag/Diagnos

Patienter söker med något/några av: smärta, svullnad, rotationssmärta, felställning.        
Vid undesökning finns ofta tydliga frakturtecken. **Distalstatus** ska alltid ingå!

##### Behandling

Slutna frakturer utan avvikande distalstatus behandlas med gipsskena och planerad kirurgi.

Målet med behandling är exakt återställande gällande längd, rotation och böjning hos radius och ulna.       
En minimalt dislocerade frakturer kan slutbehandlas med gips men opereras ofta
för att snabba på mobiliseringen.       
Även isolerad ulnafraktur fixeras i allmänhet med platta.       
Rörelseträning *kan* i allmänhet påbörjas direkt men gipsskena används ofta i 2
veckor för smärtlindring.       
Tyngre belastning undviks tills röntgenologisk läkning nåtts.

##### Prognos

**Läkningstiden** är ca 3-4 månader i normalfallet. Armkraften kan räknas vara
nedsatt långt efter skadan. Förutsatt att läkning sker utan felställning
normaliseras funktionen i allmänhet med tid.         
Vid lägre än 50 graders supination/pronation upplevs ofta begränsningar i
vardagen.

### Monteggia-fraktur

Ulnafraktur där dislokation lett till ligamentskada vilket ger dislokation hos
*caput radii* i radiohumeralleden.          
Radius kan disloceras ventralt, lateralt eller dorsalt. Klassifikation sker
enligt *Bado*       
Om även *caput radii* är frakturerat benämns frakturen monteggiaekvivalent.

##### Kliniska drag/Diagnos

I princip samma symtom som vid diafysär
underarmsfraktur ([Kapitel -@sec-diafysärunderarmsfraktur])         
**Röntgen** omfattar armbågsled och handled.

##### Behandling

**Alla** monteggiafrakturer behandlas med öppen kirugisk reposition och fixation. Efter att ulna fixerats
reponeras ofta *caput radii* utan vidare åtgärd. Reparation av ligament behövs då sällan.           
Vid monteggiaekvivalent fraktur fixeras även *caput radii*.

##### Prognos

Vid korrekt reposition blir patienten oftast besvärsfri efter läkning som tar
3-4 månader.
