---
date-modified: last-modified
---

# Nedre extremiteten

## Höft

### Perthes sjukdom {#sec-perthes}

Idiopatisk juvenil avaskulär caputnekros.

Vanligast hos pojkar i åldern 4-9. Kan dock förekomma i åldrarna 2-18. Bilateralt i 10-15% av fall.

::: {.callout-tip}

## Klassificering

**Enl. rtg-progress:**

1. Initialstadium
2. Kondensationsstadium
3. Fragmenteringsstadium
4. Utläkningsstadium

**Enligt Herring** (=grad av caputengagemang):

- **A** --- Inget engagemang i laterala pelaren.
- **B** --- >50% höjd bevarad i laterala pelaren.
- **C** --- <50% höjd bevarad i laterala pelaren.

**B/C** = Intakt men dåligt mineraliserad lateral pelare alternativt där exakt
50% av höjden kvarstår

:::

##### Kliniska drag/Diagnos

- **Symtom**
  - Smärta i ljumske, lår eller knä. Kommer ofta smygande, blir värre i rörelse.
  - Hälta
- **Fynd**
  - Inskränkt rörlighet, ffa inåtrotation
  - Hypotrofi av lårmuskler
  - Trendelenburgs tecken

Rtg verifierar diagnos men bara efter 1-2 månader. Var frikostig med upprepad
undersökning!

##### Behandling

Specifik behandling finns ej.

- **Barn <5** --- Anpassad aktivitet, NSAID i perioder med mer besvär.
- **Barn 5-8**
  - **Herring A:** Enl. ovan
  - **Andra:** 1a hand rörelseträning, 2a hand sträckbehandling,
  adduktortenotomi, centrering av caput i acetabulum (*contatinment*) genom gips, ortos, eller
  op.
- **Barn >8:** --- Containment genom op övervägs alltid vid Herring B-C. Alternativt ökas
kraniell täckning genom *shelf*-operation. I senare stadier behandlas symtom.
Ofta finns påtaglig adduktionskontraktur.

##### Prognos

Utmärkt om barnet är <5 år. Därefter gradvis sämre med ålder samt progress.

### Höftfyseolys

Typpatienten är en sent utvecklad pojke med högt BMI åldern 9-15. Men **alla** barn kan drabbas! Riskfaktorer inkluderar högt BMI, hypotyreos och D-vitaminbrist. Då flickor utvecklas snabbare har de ofta något lägre debutålder.

::: {.callout-tip}

## Klassificering

- **Stabil** = Pat. kan belasta benet utan kryckor
- **Instabil** = Pat. kan ej belasta benet --- Likställt med fraktur. Hög risk för kärlpåverkan med caputnekros som följd.

:::

##### Kliniska drag/Diagnos

- **Symtom**
  - Smärta --- I synnerhet vid instabil fyseolys då pat. ofta söker akuten.
- **Fynd**
  - Nedsatt inåtrotation
  - Gång med utåtroterat ben och hälta
  - Smärta vid passiv inåtrotation
  - Svårighet att böja höftled --- tyder på större fyseolys

Klinisk misstanke, oavsett stabil/instabil, räcker för remiss till ortopedakut.

Diagnos ställs ffa genom röntgen. Fråga specifikt för rätt projektioner! (Lauenstein/Billing)

##### Behandling

- **Lindrig-måttlig glidning** --- Fixeras  in situ med spik eller skruv.
- **Instabil fyseolys/större glidning** --- Dålig enighet om denna bör fixeras in situ eller repositioneras. Ofta görs ett försiktigt försök till sluten repositionering. Om detta inte fungerar fixeras leden in situ för att undvika avaskulär caputnekros

##### Prognos

Remodellering under tillväxt kan korrigera viss felställning. Caputnekros
behandlas som vid Perthes sjukdom ([Se -@sec-perthes]). På sikt föreligger hög
risk för höftledsprotes.

### Kongenital höftledsluxation/DDH

DDH = Developmental Dysplasia of the Hip

Inbegriper kongenitalt luxerad, luxerbar eller instabil höft. I Sverige upptäcks
~15 fall/år. 5 ggr vanligare hos flickor.

Sen upptäckt = >2 veckor postpartum. Dåligt för prognos!

Riskfaktorer:

- Ärftlighet/genetisk predisposition.
- Hormonella faktorer --- Överproduktion av östrogen/relaxin hos modern.
- Mekaniska faktorer --- Vanligare hos förstfödda och vid sätesbjudning. Även
att ett byfött barn ligger med benen utsträckta kan ge risk.

###### Kliniska drag/Diagnos

Upptäcks vid rutinundersökning av höften neonatalt med Barlows och Ortolanis
test.

::: {.callout-tip}

## DDH-tester

- **Barlows test** --- Positivt om höften luxeras med manövern.
  - Böj knä och höft till 90 grader.
  - Palpera trochanter major med en hand samtidigt som benet adduceras 10-20
  grader.
  - Tryck lätt på knät.
- **Ortolanis test** --- Positivt om höften kan repositioneras med manövern. Vid
  reposition hörs ett "*klunk*" (inte ett "*klick*"). Utförs på redan luxerad höft (spontant eller efter Barlows).
  - Knä och höft i 90 grader.
  - Stabilisera pelvis med pek+långinger mot kontralaterala trochanter major,
  tummen i ljumskvecket.
  - Abducera den höft som ska testas.

:::

##### Behandling

Höfterna fixeras med Von Rosen skena i 6-12 veckor beroende på
instabilitetsgrad. Om instabiliteten är lindrig alternativt mot slutet av
behandlingen kan Frejkabyxa användas.
