---
date-modified: last-modified
---

# Rygg

## Halsrygg

### Halsryggsfraktur/-luxation

Uppkommer hos yngre efter högenergivåld. Oftast på C0-C2 eller C5-C7. Hos äldre
efter fall i samma plan hos vilka *dens axis*-fraktur är vanligast. Även
C1-fraktur förekommer i denna grupp.             
Även traumatiskt diskbråck kan följa trauma (vanligast efter luxation).             
Vid fraktur som engagerar *foramina intervertebrae* bör skada på *a. vertebralis* betänkas.

##### Kliniska drag/Diagnos

Pat. kan ha:

- Nacksmärta
- Utstrålande smärta
- Neurologiska bortfall
- Armsmärta...

...i nästan vilken kombination som helst.

Medvetslösa patienter efter multitrauma har instabil nacke tills motsatsen
bevisats (förekommer i 25% av fall).

::: {.callout-tip}

## Fynd

- Palpabel smärta
- Smärtinskränkt rörelse
- Neurologiska bortfall
- Neurogen shock

:::

Diagnos fås ofta genom (trauma-)DT. Även MR bör utföras vid frakturmisstanke då
enbart ligamentskador kan orsaka instabilitet.

##### Behandling

**Immobilisering** från början (dvs vid misstanke).             
Skallsträck kan användas för att helt/delvis reponera felställning och luxation
i väntan på definitivbehandling.

**Alternativ beroende på skada:**            

- **Stabil skada** --- t.ex spinalutskottsfraktur
  - Fri Mobilisering
- **Medelinstabil skada i C2-C6**
  - Hård halskrage, DT-kontroll efter en vecka. Därefter individuellt upplägg.
- **Medelinstabil skada i C7-Th1**
  - Cervikothorakal ortos.
- **Instabil skada som ej lämpar sig för op**
  - Haloväst ([@sec-haloväst])
- **Instabil skada, uttallad felställning, neurologiska bortfallssymtom**
  - Operation m. korrigering av felställning, dekompression av
  ryggmärg/spinalutskott, intern fixation och fusion.

##### Prognos

Avgörs ffa av skadetyp och förekomst av neurologiska symtom.

## Ländrygg

### Lumbago {#sec-lumbago}

= Ländryggssmärta

80% av befolkningen drabbas någon gång. 80-90% av dessa blir besvärsfria inom 3 månader, 60% inom ett par veckor. Kvarstår smämrta >3 mån är prognosen sämre.

**Orsak** till smärta är ofta okänd.

::: {.callout-tip}

## Diffdiagnoser

[Internetmedicin](https://www.internetmedicin.se/behandlingsoversikter/smarta/lumbago/) har bra info om diffdiagnoser.

- Spondylodiskit
- Diskbråck
- Segmentell rörelsesmärta
- Spondylolistes (kotglidning)
- Kotkompression
- Metastas
- UVI
- Spondyloartropatier
- Spinal stenos

:::

##### Kliniska drag/Diagnos

- **Rygginsufficiens**
  - Ffa trötthetskänsla i rygg
  - Svaghet och/eller stelhetskänsla
- **Lumbago**
  - Ofta plötsligt insättande smärta vid t.ex lyft. Ej ovanligt att vakna upp med smärtan.
  - Kraftig smärta vid rörelse. Går oftast att hitta besvärsfri position.
  - Utstrålning till skinkar/ljmuskar förekommer. Ej nedanför knänivå dock.
  - Ensidig smärta relativt vanligt.
- **Ischias**
  - Smärta som strålar nedom knät i ett eller båda benen.
  - Ibland neurologisk påverkan --- Domning svaghet, nedsatta reflexer
- **Lumbago-Ischias**
  - Blandning av ovanstående

**Labb:** CRP, U-sticka, LPK, temp

Radiologi är inte nödvändig i akutskedet vid typiskt insjuknande hos äldre utan varningstecken. Vid utebliven förbättring bör MR övervägas.

##### Behandling

- Rörelse så fort som möjligt
- Råd om att gå/ligga istället för sitta. Sitt ej framåtlutad, lyft nära kroppen etc.
- Paracetamol+NSAID med *eventuellt* svag opioid vid svår smärta. **Tidsbegränsad behandling!**
- Sjukgymnastik
- Aktiv uppföljning m. ÅB inom ~4v.

### Diskbråck

Diskbråck m. ischias har ca 1-2% livstidsprevalens.

För diffdiagnoser se [Lumbago -@sec-lumbago]

##### Kliniska drag/Diagnos

- **Symtom**
  - Oftast smygande insjuknande med enbart lumbago i början. Bensmärtan är ofta
  mindre uttalad hos barn.
  - Symtom accentueras av sittande och ökat buktryck (t.ex hostning, nysning).
  - Sensorisk/motorisk störning i specifika derma-/myotom (se [ryggstatus
  -@sec-ryggstatus]).
  - **Cauda equina**-syndrom.
- **Fynd**
  - SLR --- ger smärta vid 30-60 graders flexion. Notera när smärta *nedom* knät
  upplevs.
    - Positivt omvänd SLR/Lasègue --- Talar starkt för ischias.
  - Smärtskolios --- C-formad, ökar ofta vid flexion i ryggen.
  - Smärtskolios --- C-formad, ökar ofta vid flexion i ryggen.
  - Störda reflexer/styrka/sensibilitet.
    - Undersök perianal sensibilitet+sfinktertonus samt ev.
    bulbocavernosusreflex hos män vid minsta **cauda equina**-misstanke!

##### Behandling

- **Icke-kirurgisk** --- Nästan alltid initial behandling. Uppmana till rörelse,
  påminn om god prognos. Påtala att pat. ska söka akut vid försämring samt tarm/blåspåverkan.
  - Analgetika --- Alvedon samt eventuellt NSAID. Undvik opioider. Eventuellt Gabapentin/Pregabalin vid svår ischias.
  - Sjukgymnastik
- **Kirurgisk** --- Kan övervägas efter 6-8v av utebliven förbättring eller försämring.
  - Diagnos måste fastställas radiologiskt. Tidig (<6mån) kirurgi ger bättre
  resultat.
  - Mobilisering (nästan alltid) omedelbart med försiktighetsråd om
  böjning/belastning av rygg under 2 veckor.
  - Komplikationer inkluderar duraskada/likvorläckage (4%), nervrotsskada (<1%,
  ofta ävergående inom 6mån) samt sårinfektion (2-5%).

##### Prognos

90% som inte får kirurgisk behandling blir besvärsvfria inom 6v. 80% av de som
genomgår kirurgi är nöjda med resultatet.

5-11% får recidiv i samma/närliggande kotnivå. Ung ålder, rökning och diabetes
ökar recidivrisken.

### Cauda equina-syndrom {#sec-caudaequina}

Orsakas ffa av epiduralblödning efter truma/penetration, Infektion, Tumör, Diskbråck.        
Kan uppstå akut (t.ex vid diskbråck) eller över lång tid (t.ex spinal stenos).

##### Kliniska drag/Diagnos

Akut CES ger ofta svår ryggsmärta med bilateral ischias. Vid långsammare förlopp kan ryggvärk komma smygande och följas av krampkänning bilateralt, ffa vid ryggradsextension.

- **CES-I** --- Inkomplett syndrom
  - Urinträngningar
  - Svag stråle
  - Ofrivillig flatulens
  - Ofta halvsidig/partiell ridbyxeanastesi.
- **CES-R** --- Komplett syndrom/*true Retention*
  - Total urinretention som ibland är smärtfri.
    - Man bör smärtlindra pat. då oförmåga att miktera kan bero på smärta.

::: {.callout-note}

## Fynd

- **3S**
  - Sensibilitetsnedsättning insida lår
  - Nedsatt sfinktertonus
  - Stortåflektionskraft sänkt
- Bortfallen "anal wink"-reflex

:::
