# Akut buk


**Akut buk** enligt MeSH:        

> *Kliniskt syndrom med akut buksmärta som är svår, lokal och snabbt förvärras. 
Akut buk kan orsakas av en mängd olika tillstånd, skador eller sjukdomar.*

**Olika "typer" av smärta vid akut buk:**

- **Koliksmärta:** Mer skärande, varierande smärta än inflammatoriska
    - Ileus, sten m.fl
- **Inflammatorisk smärta:** mer dov, molande, konstant värk
    - Appendicit


## The big five

- **rAAA** (rupturerat Abdominellt AortaAneurysm)
- **Tarmischemi**
- **Ileus**
- **Perforerat ulkus**
- **Pankreatit**

Innefattar de 5 **mest akuta** buktillstånden vid akut buk. Gemensamt för dem är att de oftast ger höga, centrala och/eller generella buksmärtor utan tydlig sidoskillnad.        

::: {.callout-important}

Betänk även blödning (t.ex mjältruptur) och akuta icke-kirurgiska diagnoser!

:::

### rAAA

::: {.callout-note}

## Screening

Sverige erbjuder män >65 ULJ-screening. Man upptäcker här AAA i ca 1-2% av fall.

:::

Definieras som vidgning med >1,5cm eller utbuktning på bukaorta >3cm.

Dödsorsak i ca 1% av manliga dödsfall. Dock mörkertal pga låg obduktionsfrekvens.               
Vanligare hos män än kvinnor^[Kvinnor har dock 3--4ggr högre rupturrisk vid motsvarande diameter!].

**Ruptur** sker oftast intraperitonealt eller retroperitonealt.        
Vid intraperitoneal ruptur dör patienten inom minuter. De fall som ses på akutmottagning är därför nästan uteslutande retroperitoneala. Kan även rupturera mot GI-kanalen (aortoenterisk fistel) eller *v. cava* (aortocaval fistel).        
Rupturrisk ökar exponentiellt vid storlek >5cm. Kvinnor har 3--4ggr högre rupturrisk jmf män vid motsvarande storlek!

::: {.callout-warning}

## Riskfaktorer

- **Risk för utveckling**
    - Ärftlighet
    - Manligt kön
    - Ålder
    - Rökning
    - Kronisk obstruktiv lungsjukdom
    - Bukfetma
- **Risk för ruptur**
    - Ej deltagit i screening
    - Aneurysmstorlek
    - Kvinnligt kön
    - Aktiv rökning
    - Hypertoni
    - Kronisk Obstruktiv Lungsjukdom

:::

##### Kliniska drag/Diagnos

De flesta är asymtomatiska innan ruptur.

###### Symtom

- **Icke-rupturerat**
    - Obehag, smärta
    - Upplevda pulsationer i magen
    - Tryck mot omgivande organ m. symtom därefter --- t.ex uretärer, duodenum
    - Mikroembolism
    - Trombotisk ocklusion
- **Rupturerat**
    - *Klassisk triad:*
        - Kraftig, akut buksmärta m. utstrålning mot ryggen
        - Blodtrycksfall, takykardi, svimning
        - Pulserande resistens i buken --- Kan vara svårpalperad pga fetma eller lågt blodtryck
    - Illamående, kräkningar
    - Hematemes vid aortoenterisk fistel (mycket ovanligt)

###### Fynd

- Pulserande, breddökad resistens i buk --- Avsaknad utesluter ej rAAA
- Ev. peritonitstatus
- Ev perifera ischemitecken vid mikroembolisering

##### Handläggning

###### Rupturerat AAA

- Syrgas
- Infarter
- Vätska ENDAST vid manifest cirkulatorisk chock.
    - Mål är talbar patient
- Smärtställning
    - Opioid, små upprepade doser
- **Urakur DT**-aorta
    - Inled utan kontrast. Vid indikation för endovaskulär intervention ges kontrast.
- **Vid DT-bekräftad rAAA:**
    - Urakut öppen kirurgi
      *eller*
    - Urakut endovaskulär aneurysmrekonstruktion (EVAR)

###### Ej rupturerat AAA

**Indikationer för kirurgi:**

- Storlek >5,5cm
- Symtom
- Ischemiska symtom (ocklusion, embolisering)
- Expansion >0,5cm på 6mån --- Kan vara mätfel, mer relativ indikation än ovanstående

Kirurgiska metoder är desamma som vid rupturerat AAA.

###### Val av op-metod

Yngre (<70-75) opereras med fördel öppet då risken för reruptur är lägre än vid EVAR.        
DT-angio av hög kvalité är en absolut förutsättning för EVAR.

::: {.callout-tip}

## Uppföljning

Efter **öppen kirurgi** utförs kontroll efter 30 dagar och ett år.            
Efter **EVAR** kontrolleras patienten under hela livet.^[pga komplikationer som graftmigration, endoläckage och graftskänkelocklusion] Om resultatet är utmärkt efter 30 dagar planeras nästa DT-kontroll efter 5 år.

ULJ-uppföljning hos icke opererade patienter görs beroende på storlek:        
3--3,9cm --- Vartannat år        
4--5cm --- 1 gång/år        
5--5,4cm --- 2 ggr/år

AAA >4,5cm bör remitteras till kärlkirurg för bedömning.

:::

### Tarmischemi

Ovanligt men mycket allvarligt. Slutstadiet är nekros vilken börjar i mukosan och rör sig utåt mot serosan. Detta leder till bakterieutvandring och perforation.

::: {.callout-note}

## Tarmens kärlförsörjning


```{dot}

digraph G {
    rankdir = LR

    node [style = filled; color = "red"; shape = "rectangle"]
    aorta [label = "Aorta"]
    TC [label = "Truncus celiakus\n\nKan komprimeras av diafragma och ge ischemi\nBör övervägas hos yngre"]
    AMS [label = "A. mesenterica\nsuperior\n\nSjukdom ger oftast tarmischemi/-angina"]
    AMI [label = "A. mesenterica\ninferior\n\nSjukdom ger oftast ischemisk kolit\nVänsterkolon kan dock överleva ocklusion pga AMS-kollateraler"]

    
    node [style = filled; color = "cornsilk3"; shape = "rectangle"]
    distd [label = "- Distala duodenum\n- Jejunum\n- Ileum\n- Högerkolon\ntom Payers punkt"]
    
    node [style = filled; color = "cornsilk4"; shape = "rectangle"]
    Höger2 [label = "- Distala transversum\n- Vänsterkolon\n- Proximala rektum"]
    
    node [style = filled; color = "darkkhaki"; shape = "rectangle"]
    eso [label = "- Esofagus\n- Ventrikel\n- Proximala duodenum\n- Lever\n- Mjälte"]
    
    aorta -> {TC; AMS; AMI}
    TC -> {eso}
    AMS -> {distd}
    AMI -> {Höger2}
}

```

:::

De flesta har kollateraler mellan tarmens kärl. Långsam ocklusion leder därför i allmänhet ej till nekros.

:::

###### Orsaker

- **Arteriell embolisering**
    - Står för 50% av alla fall. Drabbar oftast i *a. mesenterica superior*.
    - Synkron embolisering (Nära i tid emboli till annat organ) är vanligt. Försök alltid hitta källan!
    - Sker oftast distalt om *a. colica media*:s avgång.^[ACM försörjer proximala jejunum och kolon]
- **Arteriell trombos**
    - Står för ca 25% av alla fall. Också vanligast i *a. mesenterica superior*.
    - Kan ibland ge upphov till NOMI
    - Vid långsamt progredierande sjukdom finns ofta utbredd kollateralcirkulation. Tarmangina kan då uppträda endast efter måltid eller vid global ischemi (blodtrycksfall, syrebrist, anemi m.m)
        - Vid *kronisk trombotisering* ger den reversibla ichemin med tid atrofi och nekros av tarmmukosan.
    - *Akut trombotisering*
        - Sitter ofta vid övergången Aorta->AMS och ger därför (ofta) mer utbredd ischemi än den kroniska formen.
        - Utlöses t.ex av försämrad cirkulation, dehydrering och koagulopatier.
- **Icke ocklusiv tarmischemi (Non-occlusive Mesenteric Ischemia --- NOMI)**
    - Står för <25% av alla fall. Drabbar ffa patienter med ateroskleros i tarmkärl.
    - *Möjliga orsaker:* Cirkulatorisk svikt, hjärtinfarkt, Läkemedel^[t.ex digoxin, vissa inotropa lm (t.ex NA!)], Uttalad aortainsufficiens, större bukkirurgi, dialys, intraabdominell hypertension eller kompartmentsyndrom.]
    - **Vanligaste orsaken** till ischemisk kolit.
- **Venös tromboembolism**
    - Ovanligaste orsaken till ischemi.
    - Mer begränsad utbredning och mer smygande symtom än övriga.
    - *Orsaker:*
        - Primär koagulationsrubbning
        - Sekundärt till Levercirrhos/portal hypertension, Malignitet, Njursjukdom, Dehydrering, Obesitas.

##### Kliniska drag/Diagnos

###### Symtom {#sec-tarmischemisymtom}

Symtombilden är oftast liknande vid arteriell sjukdom oberoende lokalisation. AMS ger dock mest symtom pga få kollateraler.

Vid **akut ischemi** sker insjuknandet ofta i tre faser:

1. **Akut påkommande symtom, längd räknas i timmar**
    - Diffus/central buksmärta, oftast utan utstrålning
    - Ofrivillig/akut tarmtömning (ofta utan blod till at börja med)
    - Ev. illamående/kräkningar
2. **Längd räknas i timmar**
    - Smärtor minskar då peristaltik avtar och nekros börjar sprida sig->minskad ischemisk smärta.
    - Illamående, kräkningar pga begynnande paralytisk ileus.
3. **Längd räknas i dygn**
    - Smärtor ökar, blir mer utbredda än tidigare
    - Blodiga avföringar då mukosan går i nekros
    - Feber, allmänpåverkan, nekros ger bakterieläckage, perforation

**Tarmangina** ger ofta...

- (ofta) Långvarig postprandiell smärta
- Viktnedgång pga *fear of food*. De saknar alltså inte aptit.
- Diarréer, ofta med blod pga villusatrofi --- Blodiga diarréer bör föranleda halvakut handläggning!

Ovanstående kan ge misstanke om malignitet och patienterna är ofta koloskopiutredda.

**Icke ocklusiv tarmischemi (NOMI)**

Kan gå med akut eller subakut insjuknande. Vid akut liknar förloppet ofta arteriell tarmischemi.        
Bör alltid övervägas vid akut--halvakut tarmparalys med växande bukomfång och stigande infektionsparametrar!

**Venös trombos**

Ger ofta mer diffus symtombild pga mer begränsad omfattning.        
Symtom har subakut debut och längre duration jmf ovanstående. Blodiga diarréer ska föranleda akutremiss till kärlkirurg.

###### Fynd

- Sammanfallen buk, senare uppblåst
- Tarmljud
    - Normala/stegrade i början, därefter tyst buk.
    - Ev. blåsljud i epigastriet --- hos 50% med stenos i AMS
- Muskelförsvar
    - Saknas tidigt
    - Kommer då tarmen går i nekros
- PR --- ev. blodig avföring

###### Labb

- **LPK** --- Ospecifikt men snabbt och sensitivt
- **D-dimer** --- Som LPK
- **Laktat** --- Ospecifikt och långsamt
- Hb
- CRP --- Stiger efter ca 12h. Ses även vid t.ex aortadissektion
- Troponin
- Glukos
- Leverstatus
- Amylas
- Blödningsstatus
- Blodgruppering/BAS-test

##### Handläggning

**DT-angio buk** är den viktigaste akuta undersökningen! Prata direkt med rtg-jouren. Trefasundersökning med fina snitt över bukkärl krävs! Krea är ofta lätt förhöjt pga dehydrering. Sätt in adekvat vätska men låt ej detta hindra undersökning.

**Angiografi** är mest tillförlitlig. Kan kombineras m. endovaskulär åtgärd.

- *Aktuellt*
    - OPQRST
    - Ändrade avföringsvanor? Blod PR?
    - Viktnedgång?
    - Nyligen sjukdom med cirkulationspåverkan?
    - Smärtstillning på morfin? --- Dålig smärtstillning talar för ischemisk smärta
- *Tidigare sjukdomar*
    - Buk-OP?
    - Diarré?
    - Arteriella/venösa tromboser/embolier
- *Nuvarande sjukdomar*
    - Känd aterosklerotisk sjukdom?
    - Känd embolikälla?
    - Synkron embolisering?
    - Övriga tillstånd m. ökad risk för embolier?

- Bedöm ABCDE
- EKG bör värderas. Sätt V-sond vid kräkningar då paralytisk ileus ofta finns.
- Syrgas 10L vid SpO~2~ <98%, 5L om SpO~2~ >98%.
- 2 minst gröna infarter
- Vätska --- Kristalloid eller NaCl vid uttalade kräkningar
    - CAVE: Försiktighet vid misstanke om rAAA! Dessa patienter ska helst ej ha systoliskt >100mmHg.
- Smärtstilla --- Små doser morfin eller ketogan vid njursvikt
- V-sond, ev. KAD
- Säkra odlingar
- **Farmakologisk behandling**
    - Antibiotika pip-tazo --- Minskar bakteriell genomvandring
    - Heparin/LMWH --- Heparin tills kirurgi bedöms som avslutad pga kortare halveringstid
    - Ev. lösning av vasospasm --- Glukagon eller papaverin iv
    - Vasopressorer --- Vid hypotension. Använd beta-adrenerga preparat för att inte förvärra eventuell NOMI!
    - Rehydrering --- 2000ml 5-10% buffrad glukos + 2000ml Ringer under dygn 1 (till hjärtfrisk).
    - Korrigera elektrolytrubbning vid behov.
- **Kirurgiska behandlingsalternativ**
    - *Laparotomi* --- Embolektomi och revaskularisering. Ev. tarmresektion om avgränsat parti drabbats.
    - *Endovaskulär revaskularisering* --- Kan vara förstahandsval. Endoskopisk "second look" vid minsta tvivel om tarmens livsduglighet!
- **NOMI** --- Kräver multidisciplinär handläggning för att behandla bakomliggande tillstånd.
    - Ev. stentning av AMS
    - Använd *EJ* alfa-adrenerga lm
- **Venös trombos**
    - Ofta heparin/LMWH följt av NOAK. Vid hotandee/manifest nekros krävs dock invvasiv behandling.
    - Trombolys via kateter har ej evidens men kan vara bra.
- **Tarmangina**
    - Koloskopi på misstanke om malignitet
    - Remiss halvakut DT-angui
    - Remiss till kärlkirurg för ev. endovaskulär behandling
    - Om endast 1 tarmartär är ockluderad bör andra orsaker till smärta övervägas

### Ileus

Delas in i mekanisk samt paralytisk ileus.

- **Mekanisk ileus**
    - *Tunntarm:*
        - Adherenser
        - Herniering
        - Tunntarmsvolvolus
        - Invagination
        - Intralumenal obstruktion --- Chrons, Gallstensileus^[Fistulering mellan
        gallblåsa och tarm->större gallsten i tarm->Obstruktion. Ovanligt.],
        neuroendokrin tumör, NSAID-utlöst striktur, Pylorusstenos, Främmande
        kroppar.
    - *Tjocktarm:*
        - Intralumenal obstruktion --- Malignitet, Stenos, Fekalom, Stenosering
          av tarmanastomoser
        - Kolonvolvulus
        - Bråck
        - Akut pseudoobstruktion av kolon --- *Ogilvies syndrom*, rubbning av
        autonom innervation ger förlorat tonus.
- **Paralytisk ileus**
    - Postoperativt
    - Peritonit
    - Tarmischemi
    - Missbruk
    - Läkemedel
    - Elektrolytrubbningar

##### Kliniska drag

###### Symtom

- **"Klassisk" triad:**
    - *Buksmärta*
        - Mer akut vid tunntarmshinder(sekunder--minuter(/timmar)) jmf vid kolonhinder.
        - Typiskt intervallartad. Konstant smärta talar för strangulation med
        cirkulationspåverkan.
    - *Kräkningar*
        - Ju mer proximalt hinder desto tidigare kommer kräkningar.
        - I allmänhet viss symtomlindring efter kräkning.
        - Luktar ibland "fekalt" pga bakterieöverväxt i tunntarmen.
        - Kan likna "kaffesumpskräkningar".
        - Ventrikelretention kan ge "försenade" kräkningar. V-sond ger svar på huruvida
        detta föreligger.
    - *Avföringsrubbning*
        - Tunntarmsileus --- Smärtdebut kan ge ofrivillig defekation. Avföring upphör helt
        efter 6--12h. Flatulens upphör ofta innan dess. Vid inkomplett hinder föreligger ofta flatulens och uttalade diarréer.
        - Tjocktarmsileus --- Börjar ofta som långvarig diarré och/eller förstoppning innan
          totalt hinder föreligger varefter avförhing slutar helt.
- **Strangulationssymtom** --- Kraftiga, konstanta smärtor/"Pain out of proportion". Se även
  [kapitel @sec-tarmischemisymtom].
- **Övriga symtom**
    - Dehydrering
    - Rubbad syra-basbalans
    - Cirkulationspåverkan (senare chock)

##### Handläggning

- **ABCDE**-bedömning
- **Smärtlindring** --- Gärna tidigt vid svår smärta. I synnerhet vid samtidig hjärtsjukdom!
- **Anamnes**
    - Smärtanamnes --- *OBS* på konstant smärta som kan tyda på strangulation!
    - GI-anamnes --- Kräkningar, avföringar, gasavgång
    - B-symtom/symtom talande för kolonmalignitet
    - Tidigare/nuvarande sjkd
    - Läkemedel
    - Allergier
- **Status**
    - Vitalparametrar
    - Lung-/hjärtstatus
    - Komplett bukstatus
        - Tarmljud? --- Hjärtljud som fortleds ned i buken kan tala för vätskefyllda tarmar.
            - Metalliska, klingande patognomt för ileus (Ska låta som vatten som droppar i
            en grotta/på plåttak). Avsaknad utesluter ej.
        - Glöm ej bråckportar!
    - PR --- Palpabel tumör? Fekalom? Blod? Tom ampull?
- **Labb**
    - LPK, CRP
    - Krea
    - Hb
    - Elstatus
    - Blodgruppering, BAS-test, PK, APTT
    - Glukos
    - U-sticka
    - Graviditetstest
    - Leverstatus
    - Amylas
    - Troponin
    - Laktat --- Sen stranguleringsmarör
    - D-dimer
    - Venös blodgas
- **Övrigt initialt**
    - EKG
    - V-sond

###### Bilddiagnostik

::: {.callout-important}

GBP-opererade patienter med slitsherniering kan ha svårvärderad klinik och falskt negativa
röntgenfynd! Konsultera erfaren kollega.

:::

**Undvik bilddiagnostik** vid:          

- Allmänpåverkad eller instabil patient med hög misstanke.
- Palpabelt bråck hos patient med ileussymtom. Reponera bråck och överväg akut-op först!
- Betänk fosterrisker vid gravid patient och involvera obstretriker.

**Frågeställningar:** Fri gas? Vidgade tarmpartier? Gas-/vätskenivåer i tarm? Tumör?

- **DT-BÖS**
    - Standardundersökning
- **DT-buk med kontrast**
    - Indicerad i akutskedet vid misstanke om ischemi i tarmvägg samt vir akut-op av
    kolontumör.
- **ULJ**
    - I normalfallet ej ett alternativ. Möjligtvis hos barn m. riktad frågeställning.
- **Passageröntgen** --- Upprepad slätröntgen med kontrastmedel som stimulerar peristaltik
  och drar in vätska i tarmlumen.

##### Behandling

###### Reponering av bråck

**Bråck** ska som grundregel reponeras på akuten med smärtlindring och avslappnande (t.ex
morfin + benzodiazepin).        
Undantaget är bråck som stått länge och redan misstänks ha gått i nekros. Rodnad och ömhet i huden *kan*
vara ett tecken på detta. Dessa ska opereras akut.       
*Lyckad reponering* -> Observera pat. på akuten i 8--12h för eventuell ischemi och
perforation.        
*Misslyckad reponering* -> Akut op

###### Konservativ behandling


**Tunntarmsileus:**         
Som regel ska de med förstagångsepisod opereras oavsett grad av hinder.         
Om tecken på strangulation/akut komplikation ej föreligger kan behandling bestå av:

- Fasta
- Rehydrering
- Avlastning m. V-sond
- Passageröntgen

...under 12--24h.

**Tjocktarmsileus:**        
Obstipation/fekalom -> I första hand vatten-olje-lavemang. Eventuell manuell plockning          
Sigmoideumvolvolus -> Överväg tarmsond

**pseudoobstruktion:**          
I princip samma som övriga ileus. Perforationsrisk är låg de första 48h men ökar sedan.             
*Neostigmin* eller erytromycin kan hjälpa. När cekalpoolen närmar sig 11--12cm bör
avlastning ske via koloskopi av erfaren skopist.

###### Kirurgi

Krävs i princip på de med stranuglationstecken samt de konservativ behandling ej hjälper.

**Tunntarmsileus:**             
Strangulationstecken -> Urakut kirurgi          
Annars akut kirurgi (timmar--dygn) beroende på klinik, labb m.m.

**Tjocktarmsileus:**            
Strangulation samt perforationsrisk styr brådskan i behandlingen. Cekalpoolen dilaterar
först och anses brista kring 11--12cm.         
Bör om möjligt utföras dagtid av erfaren kirurg efter diagnostik
gällande metastaser och ev. koloskopi.

**Paralytiskt ileus:**          
Beror helt på den bakomliggande orsaken.

**pseudoobstruktion:**          
Uteslut mekaniskt ileus och andra orsaker som sepsis och hjärtsvikt. I allmänhet konservativ
behandling. Resektion av tarm är sista utväg.

### Perforerat ulcus

*Ulcus perforans*, brustet magsår.

Skiljt tillstånd från blödande ulcus. Perforerade ulcus blöder mycket sällan och blödande
ulcus perforerar mycket sällan.

#### Subtyper

- **Täckt/avgränsad perforation** --- Ofta mildare, mer lokaliserat, diffust och långdragen
  bild. Konservativ behandling är vanligare.
- **GBP-patienter** --- Ulkus kan uppstå i gastrojejunala anastomosen (*marginalulkus*),
  duodenum eller den bortkopplade ventrikeln. Marginalulkus är vanligast men de andra kan vara
  svårdiagnosticerade då de inte ger fri gas i bukhålan.
- **Immunosupprimerade och äldre** --- Saknar ofta typiska symtom. Man bör vara restriktiv
  med att utesluta diagnosen utan röntgen.
- **IVA-patienter** --- Svårt att diagnosticera.

##### Kliniska drag

###### Symtom

- **Akut insättande buksmärta**
    - Initialt i epigastriet, sedan mer diffust.
    - Lättar ibland tillfälligt i ett par timmar.
- **GI-symtom**
    - Illamående, kräkningar
    - Sällan avföringsrubbning

###### Tecken

- **Cirkulatorisk påverkan**
- **Tyst tarm** pga paralytisk ileus
- **Brädhård buk**
- **Tydlig släppömhet**
- **Feber**
- **Pat. ligger helt still**

###### Labb

- **Rutinprover**
    - Hb, CRP, LPK, elstatus, glukos
    - LPK är ofta stegrat tidigt och följs av CRP inom 6--12h.
- **Diffdiagnostik**
    - Leverprover --- Amylas kan vara lätt stegrat
    - Troponin
    - D-dimer --- Normalt värde gör tarmischemi osannolikt.
- **Övrigt**
    - Koagulationsprover, bastest, blodgruppering

###### Radiologi

Radiologi utförs på cirkulatoriskt stabila patienter. Instabila patienter med **uppenbar
diagnos** bör övervägas för direkt operation.

- **Slätröntgen BÖS** --- Fångar 70--80% av perforerade ulkus.
- **DT-buk** --- Bättre än slätröntgen.

Vid typiska symtom men utan fri gas bör upprepad undersökning efter ett par timmar
övervägas.          
Endoskopi ska **aldrig** utföras vid missänkt perforerat ulkus.

##### Handläggning

1. **Initialt omhändertagande**
    - Sätt syrgas, fixa infarter, vätska
    - Smärtstillning? --- Morfin i doser om 2,5--5mg
    - V-sond
    - Ev. KAD
2. **Farmakologisk behandling**
    - PPI --- 80mg iv som bolus, därefter infusion 8mg/h    
    - Pip-tazo 4gx3 (efter säkrade blododlingar)
    - Rehydrering --- 2000ml 5--10% buffrad glukos + 2000ml ringer uner dygn 1 till
    hjärtfrisk normalviktig vuxen. Ersätt även förluster via V-sond.
    - Ev. antiemetika
3. **Kirurgi**
    - Bör utföras inom 12--24h från sumtomdebut
    - Resektionskirurgi ffa vid uttalad malignitetsmisstanke. Mycket sällan akut.
    - Visst stöd för att öppen teknik är bättre på högriskpatienter finns.

**Konservativ behandling** övervägs i undantagsfall. Ffa vid täckta/avgränsade perforationer
då patienten söker efter att tillståndet stabiliserats. Består av:          

- Fasta
- V-sond
- Syrahämning
- Antibiotika

##### Uppföljning

- Eradikera *H. pylori*
- Ev. seponering av NSAID, ASA, steroider
- Rökstopp
- PPI
- Gastroskopi efter 6v för att utesluta maliginitet.


### Akut pankreatit

##### Orsaker

- **Alkohol** --- Vanligaste orsaken hos män
- **Gallsten** --- Vanligaste orsaken hos kvinnor
- Hypertriglyceridemi
- Hypercalcemi
- Ärftliga --- CFTR, ärftlig pankreatit
- Infektion
- Obstruktion av pankreasgång --- Tumör, sfinkterdysfunktion, ampullstenos, *pancreas
  divisum*
- Ischemi
- Kroniska inflammatoriska/immunologiska sjukdomar
- Iatrogena orsaker --- Läkemedel, ERCP, Postoperativt
- Idiopatiska

##### Kliniska drag



###### Symtom

- Epigastriell smärta
    - Snabbt ökande, utstrålning till ryggen (vanligare vid svår pankreatit)
- Illamående, kräkningar

###### Tecken

- Lokal peritonealretning
- Paralytisk ileus
- Subfebrilitet
- Cirkulatorisk påverkan --- varierar från ingen till grav

##### Handläggning

###### Utredning

- **Anamnes** inkl. alkohol och gallstenssjukdom
- **Status** --- Värdera vätskebehov extra
- **Labb** --- Blodstatus, infektionsparametrar, Lever-/pankreasstatus, Glukos,
  triglycerider, ev. artärgas
- **EKG**
- **Bilddiagnostik**
    - *ULJ* --- Värdering av gallsten. Ej för pankreasdiagnostik.
    - *DT-buk* --- Hög känslighet för pankreatit. Förändringar syns dock oftast först efter
      48h.

##### Diagnos

För akut pankreatitdiagnos ska 2/3 av nedanstående vara uppfyllt:

- Akut epigastriell smärta
- Amylas > 3ggr övre normalvärde
- DT-verifierade pankreatittecken

##### Behandling

###### Ta ställning till...

- **Vårdnivå** --- Pat. med cirkulationspåverken +/- organsvikt är intensivvårdsfall.
    - *Organsvikt föreligger vid:*
        - Kreatinin > 170
        - BT < 90mmHg efter vätskebehandling
        - PaO~2~ < 8kPa
        - GCS < 13
        - Trombocyter < 80
- **Vätskebehov** --- Kan krävas 6L under dygn 1. Styrs ffa av urinproduktion.
- **Smärtstillning**
- **Antibiotika**

::: {.callout-tip}

## Bedömning av svårighetsgrad

Flertal system finns. Det mest använda är Atlantaklassifikationen:

1. **Mild** --- Utan organsvikt och lokala komplikationer.
2. **Medelsvår** --- Med organsvikt < 48h *och/eller* lokala komplikationer.
3. **Svår** --- Med organsvikt > 48h *med/utan* lokala komplikationer.

:::

###### Okomplicerad pankreatit

- **Fasta** --- Ffa pga smärta och illamående. När smärtan släpper kan intag börja enligt
  samma principer som för opererade.
- **D-sond** --- Vid kräkningar eller ventrikelretention. Påverkar ej tillfrisknandet
- **Kontroller** --- 2ggr/dag, syremättnad, puls, bltr, temp, urin
- **Provtagning** --- Daglig elstatus, blodstatus, leverstatus, CRP, krea och glukos tills
  svårighetsgrad står klar
- **Smärtlindring** --- T.ex ketogan x 4--6.
- **Vätska** --- Rikligt med klara vätskor. Ofta stora förluster även vid mild sjukdom.
  Första dygnet ordineras från akuten
- **Antibiotika** --- *Ej till okomplicerad pankreatit*
- **Trombosprofylax** --- Som andra inlagda kir-pat.
- **DT** --- Ev. 1/vecka

###### Komplicerad pankreatit

I grunden samma behandling som vid okomplicerad pankreatit. Dock oftare behov av IVA.

- **IVA** --- Indicerat vid:
    - Hypovolemi, hypotension trots vätskebehandling
    - Oliguri, anuri
    - Hypoxi
- **Vätskerkorrigering** --- Dagliga vikter, urinmätningar och elektrolyter.
    - Hypokalcemi är vanligt men behöver bara behandlas vid symtom.
    - Diures om 1000--1500ml/dygn är önskvärd.
- **Nutrition** --- Ska ha fullt stöd så länge de ej kan försörja sig själva.
    - Att ge åtminstone en del av nutritionen enteralt (vid sond) är önskvärt.
- **Smärtstillning** --- Har direkt påverkan på läkningen. Överväg EDA vid inadekvat
  smärtlindring.
- **Antibiotika** --- *Ej som profylax* endast vid tecken på infektion. Preparat beror på
  fokus.
- **Kirurgi** --- Indicerad vid infekterade nekroser utan möjlighet till dränering och där
  antibiotika ej varit effektivt
    - Vid gallstensorsakad pankreatit bör resektion övervägas i lugnt skede
    - Pseudocystor kan opereras om de ger symtom efter 6--8v.

## Klabbet

Vanligare orsaker än "*the big five*" vid akut buk.

### Appendicit

Vanligast i åldrarna 10--40.

##### Kliniska drag

- **Symtom:**
    - Smärta --- Ofta till en början mer diffus, rör sig senare mot höger fossa.
        - Blir värre av rörelse
    - Feber
    - Ofta kissnödig (pga blåsretning)
- **Tecken:**
    - Indirekt och direkt släppömhet
    - Ev. palpabel resistens

::: {.callout-info}

Barn kan alltid vara obstiperade. Kan ibland ge liknande bild hos barn.

:::

##### Handläggning

###### Vuxna

- **AIR-score**
    - 0--4 poäng: Skicka hem och kom tillbaks nästa dag.
    - 5--8 poäng: Lägg in och följ förloppet.
    - 9--12 poäng: Exploration.

::: {.callout-important}

Vuxna över 40~45 som behandlats för en appendicit och inte skoperats på 5 år ska
koloskoperas för att utesluta tumör!

:::

###### Bilddiagnostik

- **DT** --- Aldrig aktuellt hos barn.
- **ULJ** --- Kräver van undersökare. Relativt dåligt sensitivitet. Sällan aktuellt i
  akutskedet.
