# Rektum

## Hemorrojder

Mycket vanligt, ~25% av alla >50 har besvär.

**Inre hemorrojder** utgår ovanifrån *linea dentata*, är täckta av anorektal mukosa och kommer från grenar av *v. hemorrhoidalis superior*. De är oftast lokaliserade kl. 3, 7 och 11 (Sett med patienten i ryggläge)        
**Yttre hemorrojder** utgår strax nedanför de inre och är täckta av hud.

::: {.callout-tip}

## Klassificering

- **Grad I** --- Endast belägna i övre analkanalen. Fylls i samband med krystning och ger i allmänhet endast sparsam blödning.
- **Grad II** --- Prolaberar i samband med defekation men reponerar sedan spontant.
- **Grad III** --- Förblir prolaberade men går att reponera manuellt.
- **Grad IV** --- Prolaberade hemorrojder som ej går att reponera manuellt. Slemhinnan genomgår med tid skivepitelmetaplasi och blir gråvit till utseendet.
  Yttre analhud blir flikig och trombotisering i subkutana venplexa kan ge svår smärta. Nekros kan förekomma.

:::

##### Kliniska drag/diganos

###### Symtom

- **Blödning** --- Som stänk i toalettstolen eller på pappret. Ofta ljusröd. Kan vara mörkröd vid större venös blödning i samband med kraftig krystning. Upphör i allmänhet spontant.
    - Blod kan samlas i ampullen vilket tömmer sig som koagler vi defekation. Blod kan även föras upp i kolon vid undertryckt defekation och simulera kolonblödning.
    - Kan leda till **anemi**.
- **Flytning** --- Hemorrojder som ej reponeras kan hindra förslutning av sfinktermuskulatur. Slemproducerande slemhinna hamnar då nedanför sfinktrarna vilket ger flytning och klåda.
- **Klåda**
- **Smärta** --- Relativt ovanligt. I allmänhet endast vid akut trombotisering. Då relativt
  plötslig och svår smärta.
    - *Sveda* och *ömhet* vanligare.

###### Tecken

- **Akut trombotisering** --- Ger akut smärta och ömhet. 
    - Trombotiserade hemorrojder går ej att reponera.
    - Svullnad av perianal hud och blåröd missfärgning av slemhinna över trombosplanet.
    - Prolapsen får en rosaaktig, glansig yta när ödemet tilltar.

###### Utredning

- **Rektalpalpation** --- Icke-trombotiserade hemorrojder är oftast ej palpabla. Utförs för
  att utesluta annat. 
- **Rekto-proktoskopi**
- **DT-kolon/Kolonoskopi** --- Krävs i allmänhet för att utesluta annan källa till blödning.
- **Inspektion** --- Endast hemorrojder > grad III ses.

##### Behandling

- **Grad I och II** --- I allmänhet ingen/sparsam behandling.
    - Klåda kan lindras med zinkpasta eller Silonsalva.
    - Tillfälligt ökade besvär kan lindras med analgetika supp (Xyloproct, Scheriproct,
    Alcosanal).
    - Tänk på kortisoninnehåll i salvorna!
- **Mer uttalade besvär** --- Sklerosering genom injektion, gummibandsligatur, operation som
  sistahandsalternativ.
- **Akut trombotisering** --- I allmänhet konservativ behandling. Besvär minskar i allmänhet inom dagar
  och försvinner inom 14--21 dagar. Fibrotisering i efterförloppet gör ofta att patienter
blir besvärsfria.
    - **Konservativ:**
        - Starka smärtstillande, avsvällande omslag som byts 2--3 ggr/dag.
        - Sjukskrivning 10--14 dagar är ofta lämpligt.
        - **Återbesök** efter 4--5 dagar för kontroll.
        - Besök 4--6 veckor efter attackens slut för att kontrollera resultat.
    - **Operativ** --- Till de patienter där svullnaden ej minskar och övergår i sår, nekros
      och gangrän. Dessa patienter kan gå i sepsis utan behandling.
    - **Incision** av trombotiserade hemorrojder bör *endast* göras vid analhematom.

Varierande besvär hör till hemorrojder. Långa perioder av besvärsfrihet kan följas av
perioder med svåra besvär.


